### ISSUE TITLE
addByPrivateKey method should check for the 0x prefix

### ISSUE THREAD

**Issue by man15h** [Zilliqa/Zilliqa-JavaScript-Library#157] opened 2019-08-05 23:41 UTC
**Describe the bug**
If you have a private key and if you try to access the wallet with the 0x prefix, `validation.isPrivateKey` does not notify any error(which shouldn't because it's a valid private key) but the `wallet.addByPrivateKey` method works and returns a different address. 

**To Reproduce**
1. Use `wallet.addByPrivateKey` function without `0x` prefix
2. Use `wallet.addByPrivateKey` function with `0x` prefix
3. Compare these two address

**Expected behavior**
It should check for the `0x` prefix and truncate it.

**Comment by neeboo** [comment] 2019-08-07 10:29
@man15h The problem is fixed. see https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/158

**Comment by edisonljh** [comment] 2019-08-07 10:37
Pushed to 0.7.4. Please update your package. Closing issue.

**Closed by edisonljh** 2019-08-07 10:37 UTC
