### ISSUE TITLE
Get Transaction metadata when it is broadcasted

### ISSUE THREAD

**Issue by HugoPeters1024** [Zilliqa/Zilliqa-JavaScript-Library#130] opened 2019-05-29 09:29 UTC
**Is your feature request related to a problem? Please describe.**
It is unfortunate that I can only review properties like the txid when the promise is resolved (and the transaction thus confirmed). This means I can never track unconfirmed transactions.

**Describe the solution you'd like**
`blockchain.createTransaction` returns a promise that resolves when the transaction is broadcasted. Ideally some promise with event of transaction confirmed is also exposed.

**Comment by iantanwx** [comment] 2019-05-30 02:25
Right. There are a couple of ways we can go about doing this. 

1. Return a `Promise<Transaction>`, which has to be manually confirmed. Example workflow:

```
const tx = await zilliqa.blockchain.createTransaction(...)
console.log(tx.id) // tx hash
console.log(tx.isConfirmed()) // false
const confirmedTx = await tx.confirm();
```

2. Return a `PromEmitter`, like web3.

Which is better for your use case @HugoPeters1024 ?

I've heard this feedback a few times now. I think it should be changed.

**Comment by HugoPeters1024** [comment] 2019-05-30 08:08
I am normally a C# buf, so solution 1. feels more familiair and less magic smoke. I have used 2. in the past with ethereum but never anything serious, so I find it hard to rate its merrit. 

In short, I would probably go with 1. but take it with a grain of salt because I am terribly unexperienced with 2.

Thanks for your time

**Comment by iantanwx** [comment] 2019-05-30 09:27
Right. I prefer #1 as well. Will do.

**Comment by neeboo** [comment] 2019-05-30 17:17
try adding a simple EventEmitter and attach to Transaction.

and then create a observedTransaction to Blockchain.

https://github.com/neeboo/Zilliqa-JavaScript-Library/blob/a88ee7bd5e292790db35ce10a39265184999d7e6/packages/zilliqa-js-blockchain/src/chain.ts#L275

**Comment by krisboit** [comment] 2019-06-10 22:55
@iantanwx #1 sounds good, also i think the same pattern should be applied to all methods that do a transaction behind, like contract deploy, contract call, etc..

**Comment by iantanwx** [comment] 2019-06-20 04:42
@krisboit I think this should be fixed now.

**Comment by neeboo** [comment] 2019-07-26 04:18
@HugoPeters1024 you can try latest dev branch see if it works for you

**Comment by edisonljh** [comment] 2019-08-14 03:30
Checking in again @HugoPeters1024 , any updates?

**Comment by HugoPeters1024** [comment] 2019-08-14 07:40
I'm afraid I stopped working for the project I mentioned earlier. I might
have a quick look myself later but am a bit busy hopping between trips.

**Comment by lokoArt** [comment] 2019-09-16 02:40
Any progress on it? The code in createTransaction still seems waiting for transaction's confirmation

```
async createTransaction(
    tx: Transaction,
    maxAttempts: number = GET_TX_ATTEMPTS,
    interval: number = 1000,
    blockConfirm: boolean = false,
  ): Promise<Transaction> {
    try {
      const response = await this.provider.send(RPCMethod.CreateTransaction, {
        ...tx.txParams,
        priority: tx.toDS,
      });

      if (response.error) {
        throw response.error;
      }
      if (blockConfirm) {
        return tx.blockConfirm(response.result.TranID, maxAttempts, interval);
      }
      return tx.confirm(response.result.TranID, maxAttempts, interval);
    } catch (err) {
      throw err;
    }
  }
```

**Comment by neeboo** [comment] 2019-09-16 04:44
> Any progress on it? The code in createTransaction still seems waiting for transaction's confirmation
> 
> ```
> async createTransaction(
>     tx: Transaction,
>     maxAttempts: number = GET_TX_ATTEMPTS,
>     interval: number = 1000,
>     blockConfirm: boolean = false,
>   ): Promise<Transaction> {
>     try {
>       const response = await this.provider.send(RPCMethod.CreateTransaction, {
>         ...tx.txParams,
>         priority: tx.toDS,
>       });
> 
>       if (response.error) {
>         throw response.error;
>       }
>       if (blockConfirm) {
>         return tx.blockConfirm(response.result.TranID, maxAttempts, interval);
>       }
>       return tx.confirm(response.result.TranID, maxAttempts, interval);
>     } catch (err) {
>       throw err;
>     }
>   }
> ```

you can see this example

https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/153

**Comment by lokoArt** [comment] 2019-09-16 05:04
@HugoPeters1024  thanks for the example. I just wonder, do library users need to wait until the transactions is confirmed? What are they chances that transaction after broadcasting will "be lost"?

**Comment by neeboo** [comment] 2019-09-18 00:42
> @HugoPeters1024 thanks for the example. I just wonder, do library users need to wait until the transactions is confirmed? What are they chances that transaction after broadcasting will "be lost"?
> 
> Reason why I'm asking: I don't want to keep all those promises in my stack and wait until they are confirmed and waste me computing resources).

Because transaction hash is actually calculated by publicKey and nonce, so that each hash can be sent to blockchain to see if the transaction is there.

One more thing, the transaction can be rejected by lookup node or rejected during the consensus. So we need to confirm ( RPCMethod.GetTransaction) to see if it is accepted and processed by blockchain

The `createTransaction` process can be divided into process below:

1. construct the transaction class/object
2. use an account/signer to sign(update nonce before signing)
3. send a signed transaction to the blockchain.
4. after getting the hash(or calculate one), use transaction.confirm(...) to confirm that transaction.

So if you don't want to keep promises in the stack. You can isolate the confirm process from the others. Just to keep transaction hashes that sent, then confirmed them whenever you like.

**Closed** 2021-09-16 06:05 UTC
